// <auto-generated />
namespace Pratice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class coin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(coin));
        
        string IMigrationMetadata.Id
        {
            get { return "202204020221000_coin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
